chmod +x *
adb shell pm enable com.google.android.gms
adb shell pm enable com.google.android.gsf
adb shell pm enable com.android.vending
adb shell pm enable com.google.android.googlequicksearchbox
adb shell pm enable com.google.android.gms
adb shell pm enable com.google.android.gms.location.history
adb shell pm enable com.google.android.apps.googleassistant
adb shell pm enable com.google.ar.lens
adb shell pm enable com.google.android.contacts
adb shell pm enable com.google.android.dialer
adb shell pm install com.google.android.gms
adb shell pm install com.google.android.gsf
adb shell pm install com.android.vending
adb shell pm install com.google.android.googlequicksearchbox
adb shell pm install com.google.android.gms
adb shell pm install com.google.android.gms.location.history
adb shell pm install com.google.android.apps.googleassistant
adb shell pm install com.google.ar.lens
adb shell pm install com.google.android.contacts
adb shell pm install com.google.android.dialer